### ISSUE TITLE
FutureWarnings from pyproj

### ISSUE THREAD

**Issue by pseyfert** [MatthewDaws/TileMapBase#17] opened 2020-02-23 21:08 UTC
since upgrading 2.4.0 to 2.5.0 I get `FutureWarning`s when running TileMapBase.

E.g. the notebook plotting over basemap prints after the first cell
```
%matplotlib inline
import matplotlib.pyplot as plt
import tilemapbase

tilemapbase.init(create=True)
```
the following printout
```
/usr/lib/python3.8/site-packages/pyproj/crs/crs.py:55: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/usr/lib/python3.8/site-packages/pyproj/crs/crs.py:55: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/usr/lib/python3.8/site-packages/pyproj/crs/crs.py:55: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/usr/lib/python3.8/site-packages/pyproj/crs/crs.py:55: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
```

I have to admit that after some superficial looking over the tilemapbase code I don't see if this stems from to-be-updated code within tilemapbase or from anything else in the call/dependency tree.

**Comment by MatthewDaws** [comment] 2020-02-24 20:48
So I think you must mean you have updated _pyproj_ to version 2.5.0.

Once I installed pyproj 2.5.0 I too get the same warnings as soon as I do

> import tilemapbase

**Comment by MatthewDaws** [comment] 2020-02-24 20:56
So the problem is that I am using old `pyproj` code.  See http://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1

I will get around to updating the code and testing in a couple of weeks.

**Comment by nlcircle** [comment] 2021-01-10 13:39
Hey Matthew,

First of all, my compliments for the Tilemapbase package. Truly helpful in quick displaying OSM backgrounds in radar display.

Not sure if I've looked in the right places, but my yesterday's install of Tilemapbase (so presumably the most recent version from PyPI) still generates those future warnings. It doesn't seem to be an issue w.r.t. using Tilemapbase (yet) but it would be great if those warnings could be 'silenced' via an update of the Tilemapbase code. 

Hope you can shed some light on what to expect in this situation or about any solutions to remove those warnings and keep using Tilemapbase.

Greetz,
Rene

**Comment by MatthewDaws** [comment] 2021-01-11 21:30
I see that "...in a couple of weeks" became "...in a year's time".  It feels like half a lifetime.  I guess a certain virus can be blamed.

`pyproj` seems under active development, and is now on version 3.0, so I am happy to just drop support for version 1 entirely, and move to the v2 API.  On testing, I found that with v2.1.x you get a new warning:

    pyproj\transformer.py:92: UserWarning: `from_crs` is deprecated and will be removed in 2.2.0. Please use `from_proj` instead.
    "`from_crs` is deprecated and will be removed in 2.2.0. "

This disappears with a later version, and all the docs _continue_ to use `from_crs` so I guess the developers of `pyproj` changed their minds.

**Comment by MatthewDaws** [comment] 2021-01-14 21:10
Using Anaconda on Windows, I get new warnings about the `collections.abc` package, but after some investigation, I am sure this is coming from the `pyreadline` package, and not any of my code.

**Comment by MatthewDaws** [comment] 2021-01-14 21:10
I'll close this issue, and have a look at the remaining issues (and some new ones today) before I release a new version.  But the main branch on GitHub is working already.

**Closed by MatthewDaws** 2021-01-14 21:10 UTC
