### ISSUE TITLE
Future warning: deprecated syntax

### ISSUE THREAD

**Issue by james-willcox** [MatthewDaws/TileMapBase#22] opened 2021-01-13 22:51 UTC
FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))

**Comment by MatthewDaws** [comment] 2021-01-14 21:16
Duplicate of
https://github.com/MatthewDaws/TileMapBase/issues/17

Now fixed.

**Closed by MatthewDaws** 2021-01-14 21:16 UTC

**Comment by james-willcox** [comment] 2021-01-18 23:57
Thanks
